### ISSUE TITLE
missing requirements.txt file

### ISSUE THREAD

**Issue by tanay2001** [zide05/AdvFact#1]
Hi,

I was trying to use the framework on a custom dataset but I am unable to figure out the correct version for the `benepar` dependency. The latest version supports `BeneparComponent(benepar_en3)` while the code uses `BeneparComponent(benepar_en)` which is leading to some unwanted errors while defining the nlp.pipeline ..

Would appreciate your help in this regard

Thanks!

**Comment by zide05** [comment]
Hi, Sorry for the untimely reply. I have updated the code relating benepar_en in the code.
